notifications:
  email: false

env:
  global:
  - TERM=dumb
  - secure: R9F/N9Df/YFBEQLc+k7aU9RjYT2B/RdVbVH4LRuOW38/mY5lCrHhZPHE1wP9cy3tjxT/x+vvqpw0Q+P8x/sW2LSbokUXWQH00+zMFJC6xM8ZflOWFR2Z7Jxqj+jj2GITPqY4OZ/NqjLblBXrUtu+qJOaxBvL9+iCwUGef/aRujGxUeW60CyVzqxwXZOAaQH27aEHFXvnh1OsR0ii+jzin3YAtiIqWJgs4lzmW51w+D2ih4ftLFwFoCNI1Z0Cr2ErEM09aTtaGT8Xd5fYwOMN1SEvAmXzIqMW92hfPc7lSy2at4MuHiZL/HmzyjoCBdySHoT1FsAfP9G7dzmdI0Vu5Y9rOh1DLAio8CsKnhjyPubcvn7ApBolfbf3d/hOKRKUIVUpBux6Tk8VfS8qmkwRJ8xn+2q/evje2NlWdPyfukpIF3Nh3XpB1D5rQFToeCuUJCIxGX7eDYuPQxATf8KBN+BcxQlYl45AFsRgbA9WRdYzVq/8GgrRPBZy4GbH+aM72z+zhWWzqJ8x37hamy4ss+xyO+CdTXd4CVM0LAVxkelf9tZraeJlXiTgnZpX3gF/pRpOE9+5FTDThQ6sRazc4NkNXNn7+5Vl/0Er5A5SEN5G5uTTT+IvecRoGyNVnA32sQRyEv4eeWvejwHfG+V+K9jAPcL6biSQXzw/sY80LMA=

language: java
jdk:
- oraclejdk8
#- oraclejdk10

service:
- docker

addons:
  apt:
    sources:
    - google-chrome
    packages:
    - google-chrome-stable
    - libappindicator1
    - fonts-liberation
    - bash
    - curl
    - libxml2-utils
    - docker-ce

install: true
before_install:
- export CHROME_BIN=/usr/bin/google-chrome
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
#
- sudo add-apt-repository universe -y >/dev/null
- echo "deb http://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list >/dev/null
- sudo apt-get update -yqq >/dev/null
- sudo apt-get install -yqq --no-install-suggests --no-install-recommends
  tree jq python-pip curl bash sudo >/dev/null
#
- sudo pip install docker-compose httpie >/dev/null 2>&1
#
- source <(curl -s https://raw.githubusercontent.com/daggerok/bash-functions/master/main.bash)
- stop_any 8080 3000 80 >/dev/null
#
- curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add - >/dev/null
- echo "deb https://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list >/dev/null
- sudo apt-get update -yqq >/dev/null
- sudo apt-get install -yqq --no-install-suggests --no-install-recommends yarn >/dev/null

script:
- export root=$(pwd)
#
# maven
- ./mvnw >/dev/null
- java -jar app/target/*-all.jar &
- wait_for 5050
- http :5050
- http :5050/ololo
- stop_any 5050 80
# gradle
- ./gradlew >/dev/null
- java -jar app/build/libs/*-all.jar &
- wait_for 5050
- http :5050
- http :5050/ololo
- stop_any 5050 80

before_deploy:
- cd ${root}
- ./mvnw -Pdocs
- ./gradlew documentation
- mkdir -p ./target/generated-docs
- cp -Rf ./target/generated-docs/index.html ./target/generated-docs/404.html

deploy:
  provider: pages
  skip-cleanup: true
  # travis encrypt GITHUB_TOKEN=<your github repo token> --add
  github-token: "$GITHUB_TOKEN"
  keep-history: true
  on:
    branch: master
  local-dir: target/generated-docs
  target_branch: gh-pages

before_cache:
- for item in $(find ~/.gradle -name "*.lock");
    do sudo rm -rf $item ;
  done

cache:
  directories:
  - $HOME/.m2
  - $HOME/.gradle
  - $HOME/.docker
